### ISSUE TITLE
Disable auto-display darkening

### ISSUE THREAD

**Issue by mich2k** [lawleagle/oled-linux#2]
hello, is there a way to disable the display brightness turning auto off?
I do not think is a system settings since without this script running the display keeps awake for around 15min
thanks

**Comment by lawleagle** [comment]
You mean the display dimming itself? I like that, but it's a system setting, not oled-linux. 

Here's my reasoning:
It's not just you who changes the brightness files when you press the `BrightnessUp` and `BrightnessDown` keys, the system also changes those brightness files as if it would be a normal screen, so oled-linux applies those changes to the screen too.

That way, when the OS dims the screen, it will actually get dimmed, but without this script, there wouldn't be anyone to update the brightness of the display when the OS changes those files, so it gives the impression that this script dims the display while it's actually just the OS doing it's job and the script functioning as intended.

PS: Feel free to reopen this or to open another issue if I didn't understand properly what the problem is.
