### ISSUE TITLE
8% idle cpu usage

### ISSUE THREAD

**Issue by gavsiu** [lawleagle/oled-linux#5]
I don't have an OLED screen, but my backlight does not work. This script helps make it easier for me to change my brightness using xrandr, but 8% idle cpu usage seems a bit high. It's even higher than Firefox idling with 11 tabs open. What's causing it and can we reduce this somehow? I'm not using redshift. I turned that off in the config and did not load the optional scripts.

**Comment by lawleagle** [comment]
I see 2 issues here instead of one, so I'll tackle them from most important to least important.


High CPU usage
----------------------------------------
This script basically does nothing until someone modifies the backlight file. `inotifywait` does just that, waits until the backlight file is modified, so the 8%CPU usage is definitely coming from somewhere else. On my machine the CPU usage is fine, so as it doesn't happen on my machine and the logic seems to be good, I'll consider this resolved. You can reopen this if it's necessary, or we can tackle this together on Discord, if you want.


This project on NON-OLED displays
----------------------------------------
I don't recommend using this on a display that is not OLED, as is wouldn't really get the job done (unless you change your xrandr command to use actual brightness and not color-correction, like this project is using by default)

OLED displays are different, as the amount of light they emit is also based on the color they emit, so on OLED displays, changing the color does change the brightness, which is not true for NON-OLED displays.

On NON-OLED displays, the brightness is adjusted by the backlight, so changing the color is just that, a color change and the brightness remains the same.

**Comment by GeodesicCarbon** [comment]
I would like to start by thanking you very much for saving my poor eyes. Now I can actually use my laptop at night without feeling the rage of thousand burning suns 😎 

I think I might have found out why the CPU usage is so high. If  **only** `<path-to>/oled-linux/oled-linux.sh &` is added to the `.xinitrc `then [`inotifywait (...) -e close_write './file-pipes/day-night.txt'`](https://github.com/lawleagle/oled-linux/blob/eb2faf2bb70d109416d0e304b734a82d626e4dd8/oled-linux.sh#L81) will exit with error and execute the loop as fast as possible. I solved the issue by manually creating `file-pipes/day-night.txt` file.

**Comment by gavsiu** [comment]
> I would like to start by thanking you very much for saving my poor eyes. Now I can actually use my laptop at night without feeling the rage of thousand burning suns sunglasses
> 
> I think I might have found out why the CPU usage is so high. If **only** `<path-to>/oled-linux/oled-linux.sh &` is added to the `.xinitrc `then [`inotifywait (...) -e close_write './file-pipes/day-night.txt'`](https://github.com/lawleagle/oled-linux/blob/eb2faf2bb70d109416d0e304b734a82d626e4dd8/oled-linux.sh#L81) will exit with error and execute the loop as fast as possible. I solved the issue by manually creating `file-pipes/day-night.txt` file.

Thanks man, I'm not crazy after all. This is the exact problem and solution. I did not even have to reboot or restart the script. It instantly dropped the script CPU usage to 0%.

> ## This project on NON-OLED displays
> 
> I don't recommend using this on a display that is not OLED, as is wouldn't really get the job done (unless you change your xrandr command to use actual brightness and not color-correction, like this project is using by default)
> 
> OLED displays are different, as the amount of light they emit is also based on the color they emit, so on OLED displays, changing the color does change the brightness, which is not true for NON-OLED displays.
> 
> On NON-OLED displays, the brightness is adjusted by the backlight, so changing the color is just that, a color change and the brightness remains the same.

I understand the goal of this script. As I have said earlier, I DO NOT have a working backlight on my new laptop. If I did, I would have simply used xbacklight. I am using this script as a bandaid until someone figures out how to enable backlight control on some newer Lenovo laptops.
